# TODO: Linters that should immediately added after golangci-lint has been accepted:
# - thelper
# - staticcheck
# - nilerr
# - ineffassign
# - govet
# - gosimple
# - wastedassign
# - exhaustive
# - stylecheck
# - errorlint
# - structcheck
# - unparam
# - bodyclose
# - unused
# - prealloc
# - errcheck
# - prealloc
# - gosec
# - gofumpt
# - goimports
# - gofmt
# - gocritic
# - gci
# - deadcode
# - makezero
# - revive
# - forbidigo
# - errcheck
# - forcetypeassert
# - paralleltest

# TODO: Linters that should be included to improve code quality. Not already added because bigger code changes are required. (Ordered)
# - wrapcheck: Wrap errors with more context before passing them up to. Helps understanding what happens.
# - goerr113: No dynamic errors please.
# - goprintffuncname: Encourage consistent func naming.
# - nlreturn, whitespace, wsl: Improve readability by forcing new lines at certain places.
# - godot: Comments are sentences and end with periods.
# - dupl: Duplicate code bad!
# - ifshort: Improve readability by encouraging the short if syntax.
# - goconst: encourage constants.
# - gochecknoinits: Don't use init().
# - testpackage: Encourages black box testing.
# - gochecknoglobals: Dislikes that you create globals.
# - cyclop, funlen, gocognit, gocyclo, nestif: Low complexity ftw.
# - exhaustivestruct: Be way too verbose with structs.

linters:
  disable-all: true
  enable:
    - typecheck
    - varcheck
    - asciicheck
    - depguard
    - dogsled
    - durationcheck
    - exportloopref
    - goheader
    - golint
    - gomoddirectives
    - gomodguard
    - importas
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - unconvert
