---

name: Publish quay.io/ansible/receptor:devel

on:
  push:
    branches: [devel]

jobs:
  release:
    runs-on: ubuntu-latest
    name: Push devel image
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install build dependencies
        run: |
          pip install build

      - name: Build Image
        run: |
          make container REPO=receptor TAG=devel

      - name: Test Image
        run: podman run --rm receptor:devel receptor --version

      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: receptor
          tags: devel
          registry: quay.io/ansible/
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
