name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v2
    - run: |
        go get -u golang.org/x/lint/golint
        echo "::add-path::$(go env GOPATH)/bin"
    - uses: actions/setup-python@v1
    - uses: pre-commit/action@v2.0.0
